### ISSUE TITLE
NGAME: Negative Mining-aware Mini-batching for Extreme Classification

### ISSUE THREAD

**Issue by LLLLLLoki** [Extreme-classification/deepxml#14]
I am very interested in a lot of work you do in XML, will the code for NGAME be open source

**Comment by kunaldahiya** [comment]
Hi

Thanks for your interest. Yes, we'll be releasing the code for NGAME.

**Comment by XUYANGSUN** [comment]
Is there a time point of open source NGAME code?

**Comment by kunaldahiya** [comment]
Yes. We plan to release the code alongside the WSDM conference - early next month.
