### ISSUE TITLE
Dummy example/tutorial how to use deepxml

### ISSUE THREAD

**Issue by fernandojunior** [Extreme-classification/deepxml#5]
It seems you guys have developed a great lib. But I think you could improve the documentation even more, from highest level (a tutorial how to use deepxml) to lowest level (baby steps in a jupyter nootebook how to use the lib, and/or put some docstring in the functions). This way, lot of people will meet, use, and share this cool lib.

**Comment by cairomo** [comment]
the actual use of this lib is fairly simple and included in the documentation: `./run_main.sh 0 DeepXML {DATASET_NAME} {VERSION} {SEED}`
but i agree, most of the overhead is actually preparing the data to fit the specific format. compared to fasttext, for example, which requires little data preparation.

**Comment by kunaldahiya** [comment]
@fernandojunior and @cairomo Thanks a lot for the helpful feedback. I'll try to add tutorials/documentation to further simplify things.
