### ISSUE TITLE
what is surrogate_mapping in the Model class?

### ISSUE THREAD

**Issue by cairomo** [Extreme-classification/deepxml#7]
when creating a model, there is an optional `surrogate_mapping` argument. It accepts a string, not a .npz file or what I would expect (the model from the surrogate step). can you provide an example of what a `surrogate_mapping` parameter would look like?
I am currently using labels_params.pkl in the model directory/surrogate folder.

**Comment by kunaldahiya** [comment]
Hi,

In Module-I: the model reduces the label space by using the 'surrogate_mapping' file. 'surrogate_mapping' is a plain text file containing the mapping for each label (one int in each line). Astec maps labels using a clustering-based algorithm - you can explore other algorithms as well (see tools/surrogate_mapping.py and the paper for more details).
