### ISSUE TITLE
Training the model on a custom dataset, how to?

### ISSUE THREAD

**Issue by StefanusAgus** [Extreme-classification/deepxml#8]
Hello, thank you very much for the code that you provides to easily use deepxml. I am planning to train the deepxml/astec model on a custom dataset. I wonder how should I proceed to do this?

My main concern is how to prepare the BoW features required. What type of approach is used? Thank you!

**Comment by kunaldahiya** [comment]
Thanks for trying out deepxml. You might want to look at [this example](https://github.com/kunaldahiya/pyxclib/blob/master/xclib/examples/sparse_bow_features_from_raw_data.py) which demonstrates the pipeline to create unigram based BoW features. 

PS: You might also want to look into sub-word based features (such as WordPiece) as they provide additional gains over unigram features on some applications.
