### ISSUE TITLE
No such file or directory: '/home/deepxml/data/EURLex-4K/deepxml.Astec/1024.108/data_stats.json'

### ISSUE THREAD

**Issue by AiXia520** [Extreme-classification/deepxml#9]
hello, I have gotten this model working on training data，but the file of 'data_stats.json'  cannot be generated. Could you please help me?
Traceback (most recent call last):
  File "runner.py", line 428, in <module>
    run_one(
  File "runner.py", line 376, in run_one
    return run_deepxml(work_dir, version, seed, config)
  File "runner.py", line 116, in run_deepxml
    data_stats, args.surrogate_mapping = create_surrogate_mapping(
  File "runner.py", line 33, in create_surrogate_mapping
    open(os.path.join(tmp_model_dir,"data_stats.json")))
FileNotFoundError: [Errno 2] No such file or directory: '/home/deepxml/data/EURLex-4K/deepxml.Astec/1024.108/data_stats.json'

**Comment by hdm30** [comment]
I have the same issue, please how did you resolve it?

**Comment by ThejaniYapa** [comment]
Could you figure this out?

**Comment by arina080803** [comment]
I have the same issue
